package com.yahoo.ads.adportal.entity;

// Generated Apr 12, 2012 4:50:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Contact generated by hbm2java
 */
@XmlRootElement
public class Contact implements java.io.Serializable {

	private Integer contactid;
	private Customer customer;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String addr1;
	private String addr2;
	private String city;
	private String state;
	private String zip;
	private String country;
	private String status;
	private byte[] logo;
	private String login;
	private String pwd;
	private String division;
	private Date createDate;
	private Date lastUpdate;
	private Set<Product> products = new HashSet<Product>(0);

	public Contact() {
	}

	public Contact(Customer customer) {
		this.customer = customer;
	}

	public Contact(Customer customer, String firstName, String middleName,
			String lastName, String email, String addr1, String addr2,
			String city, String state, String zip, String country,
			String status, byte[] logo, String login, String pwd,
			String division, Date createDate, Date lastUpdate,
			Set<Product> products) {
		this.customer = customer;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.email = email;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.status = status;
		this.logo = logo;
		this.login = login;
		this.pwd = pwd;
		this.division = division;
		this.createDate = createDate;
		this.lastUpdate = lastUpdate;
		this.products = products;
	}

	public Integer getContactid() {
		return this.contactid;
	}

	public void setContactid(Integer contactid) {
		this.contactid = contactid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}
	
	@Override
	public String toString() {
		return "Contact [contactid=" + contactid + ", customer=" + customer
				+ ", firstName=" + firstName + ", middleName=" + middleName
				+ ", lastName=" + lastName + ", email=" + email + ", addr1="
				+ addr1 + ", addr2=" + addr2 + ", city=" + city + ", state="
				+ state + ", zip=" + zip + ", country=" + country + ", status="
				+ status + ", logo=" + Arrays.toString(logo) + ", login="
				+ login + ", pwd=" + pwd + ", division=" + division
				+ ", createDate=" + createDate + ", lastUpdate=" + lastUpdate
				+ ", products=" + products + "]";
	}

}
