package com.yahoo.ads.adportal.entity;

// Generated Apr 12, 2012 4:50:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Cust generated by hbm2java
 */
@XmlRootElement
public class CustContact implements java.io.Serializable {

	private Integer customerid;
	private String customername;
	private String location;
	private Date createDate;
	private Date lastUpdate;
	private Integer contactid;
	private Customer customer;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String addr1;
	private String addr2;
	private String city;
	private String state;
	private String zip;
	private String country;
	private String status;
	private byte[] logo;
	private String login;
	private String pwd;
	private String division;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public CustContact() {
	}

	public CustContact(String customername) {
		this.customername = customername;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = new Date();
	}
	
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}
	
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = new Date();
	}
	
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}
	
	@Override
	public String toString() {
		return "CustContact [customerid=" + customerid + ", customername="
				+ customername + ", location=" + location + ", createDate="
				+ createDate + ", lastUpdate=" + lastUpdate + ", contactid="
				+ contactid + ", customer=" + customer + ", firstName="
				+ firstName + ", middleName=" + middleName + ", lastName="
				+ lastName + ", email=" + email + ", addr1=" + addr1
				+ ", addr2=" + addr2 + ", city=" + city + ", state=" + state
				+ ", zip=" + zip + ", country=" + country + ", status="
				+ status + ", logo=" + Arrays.toString(logo) + ", login="
				+ login + ", pwd=" + pwd + ", division=" + division + "]";
	}
	

}
