package com.yahoo.ads.adportal.entity;

// Generated Apr 12, 2012 4:50:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productid;
	private Customer customer;
	private Contact contact;
	private String name;
	private byte[] picture;
	private Double price;
	private String status;
	private String description;
	private String category;

	public Product() {
	}

	public Product(Customer customer, Contact contact) {
		this.customer = customer;
		this.contact = contact;
	}

	public Product(Customer customer, Contact contact, String name,
			byte[] picture, Double price, String status, String description,
			String category) {
		this.customer = customer;
		this.contact = contact;
		this.name = name;
		this.picture = picture;
		this.price = price;
		this.status = status;
		this.description = description;
		this.category = category;
	}

	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
